--!strict
-- GENERATED by the Move Editor (Studio: Tools > Source). Schema v3 -- see Shared/MoveTypes.lua.
-- Safe to hand-edit; writing the move from the editor again replaces this file.
--
-- Spec fixture (Tests/MoveEditor/MovePresentation.spec.lua): a stored record carrying a Presentation
-- block, in MoveSourceWriter's exact layout -- what "Write to source" leaves on disk for such a move. Not
-- under AuthoredMoves/, so AuthoredMoveLibrary's own spec never loads it.
return {
	ActiveSeconds = 0.1,
	AnimationId = "",
	AttachmentPart = "Root",
	Author = "Spec",
	Category = "",
	Cooldown = 1,
	CreatedAt = 1,
	Damage = 10,
	Description = "",
	Dimensions = {
		AngleDegrees = 90,
		Height = 5,
		InnerRadius = 0,
		Length = 5,
		Radius = 2,
		Width = 4,
	},
	DisplayName = "Presented",
	LocksMovement = false,
	MoveId = "fixture-presented-move",
	OffsetPitch = 0,
	OffsetRoll = 0,
	OffsetX = 0,
	OffsetY = 0,
	OffsetYaw = 0,
	OffsetZ = -3,
	PostureDamage = 8,
	Presentation = {
		Active = {
			Pitch = 0.8,
			SoundId = "rbxassetid://111",
			TrailColor = "None",
		},
		HitBlocked = {
			HitStopSeconds = 0.05,
			SparkColor = "#FF8800",
			Sparks = "Trade",
			Volume = 1.5,
		},
		HitParried = {
			FlashColor = "#00AAFF",
			SoundId = "None",
		},
	},
	RecoverySeconds = 0.3,
	SchemaVersion = 3,
	Shape = "Box",
	UpdatedAt = 2,
	WindupSeconds = 0.3,
}
